# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '챔피언추천.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from scipy import rand
import tensorflow
import os
import json
import random
import keras
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import input_onehot
from keras.utils import np_utils
from keras.models import Sequential
from keras.models import load_model
from keras.layers import Dense, Activation

from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import json
import AImodel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(140, 20, 94, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 60, 94, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 100, 94, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(140, 140, 94, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(140, 190, 94, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 100, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 140, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 190, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(580, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.btn_clicked)
        
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(280, 20, 401, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "아군 챔피언"))
        self.comboBox.setItemText(0, _translate("MainWindow", "라인 선택"))
        self.comboBox.setItemText(1, _translate("MainWindow", "탑"))
        self.comboBox.setItemText(2, _translate("MainWindow", "정글"))
        self.comboBox.setItemText(3, _translate("MainWindow", "미드"))
        self.comboBox.setItemText(4, _translate("MainWindow", "원딜"))
        self.comboBox.setItemText(5, _translate("MainWindow", "서폿"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "라인 선택"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "탑"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "정글"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "미드"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "원딜"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "서폿"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "라인 선택"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "탑"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "정글"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "미드"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "원딜"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "서폿"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "라인 선택"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "탑"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "정글"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "미드"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "원딜"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "서폿"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "라인 선택"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "탑"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "정글"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "미드"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "원딜"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "서폿"))
        self.lineEdit.setText(_translate("MainWindow", "챔피언 입력창"))
        self.lineEdit_2.setText(_translate("MainWindow", "챔피언 입력창"))
        self.lineEdit_3.setText(_translate("MainWindow", "챔피언 입력창"))
        self.lineEdit_4.setText(_translate("MainWindow", "챔피언 입력창"))
        self.lineEdit_5.setText(_translate("MainWindow", "내 챔피언"))
        self.pushButton.setText(_translate("MainWindow", "추천받기"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "챔피언"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "승률"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "픽률"))

    def btn_clicked(self):
        
        with open('./champion.json', 'r') as f: #mat 불러오기
            champ_list = json.load(f)
        allplayer=np.zeros(159)
        player1=self.lineEdit.text()
        player2=self.lineEdit_2.text()  
        player3=self.lineEdit_3.text()  
        player4=self.lineEdit_4.text()      
    
        for i in range(len(champ_list)):
            if champ_list[i]["name"]==player1:
                allplayer[i]=1
            if champ_list[i]["name"]==player2:
                allplayer[i]=1    
            if champ_list[i]["name"]==player3:
                allplayer[i]=1   
            if champ_list[i]["name"]==player4:
                allplayer[i]=1
        
        allplayertestdata=np.zeros(159)   
        
        #dataset=input_onehot.q()
        #X=dataset[:,0:159]
        #y=dataset[:,159]
        
        #X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=1)
        '''
        n = AImodel.DenseDegressive(Xlist=X_train, ylist=y_train, n_hidden_layers=5, NN=1024, dropout=0.2, batch_size=1000, epochs=10)
        result=n.build()
                #print(result)
        '''       
        model=keras.models.load_model("lol_model.h5")        
        model.summary()
        #history=model.fit(X_train, y_train, batch_size=1000, epochs=100)     
        allplayertest=allplayer
        print(allplayertest)
        print(allplayer)
        for j in range(len(champ_list)):
            #allplayertest=allplayer
            if allplayer[j]==0:
                allplayertest[j]=allplayertest[j]+1
            
                
                allplayertestdata[j] = model.predict(allplayertest)
            else:
                allplayertestdata=0.0    
                
            allplayertest[j]=allplayer[j] 
                
            
        sort_index = allplayertestdata.argsort()
        champion_1=champ_list[(sort_index[0])]["name"]
        champion_2=champ_list[(sort_index[1])]["name"]
        champion_3=champ_list[(sort_index[2])]["name"] 
        print(champion_1,champion_2,champion_3) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())